LIBS = -lcommons -lcspecs -lreadline ../src/mdj.c ../../Bibliotecas/sockets.c ../../Bibliotecas/helper.c

borrar_archivos:
	gcc -pthread -o borrar_archivos test_borrar_archivos.c $(LIBS) 

clean:
	-rm -f *.o
