LIBS = -lcommons -lcspecs -lreadline ../src/mdj.c ../../Bibliotecas/sockets.c ../../Bibliotecas/helper.c

validar_archivo:
	gcc -pthread -o validar_archivo test_validar_archivo.c $(LIBS) 

clean:
	-rm -f *.o
