TARGET = test_crear_archivos
LIBS = -lcommons -lcspecs
program:
	gcc -I/home/daniel/tp-2018-2c-Nene-Malloc/mdj/tests/unit-tests -o $(TARGET) test_crear_archivos.c $(LIBS)
clean:
	-rm -f *.o
	-rm -f $(TARGET)
