TARGET = fm9
LIBS = -lcommons -lreadline
program:
	gcc -pthread fm9.c -I/home/utnso/workspace/tp-2018-2c-Nene-Malloc/fm9/src -o $(TARGET) $(LIBS) ../../Bibliotecas/sockets.c
clean:
	-rm -f *.o
	-rm -f $(TARGET)
